### Test Auth
GET http://localhost:7777/api/v1/auth/1

### Autenticacion
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{
  "email": "lramirez@gmail.com",
  "password": "ABCabc123"
}

### Ejemplo con valores vacios
POST http://localhost:7777/api/v1/auth/
Content-Type: application/json
Accept: application/json

{

}
